repos:
-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: v2.0.1
    hooks:
    -   id: puppet-validate
        # TODO: Remove this version pinning. The problem here seems to be that
        # the Debian-packaged versions of the semantic_puppet gem
        # (ruby-semantic-puppet package) cause some kind of error with locale
        # loading for puppet validation. A bug probably needs to be opened with
        # the Debian package maintainers or with semantic_puppet depending on
        # who is actually causing the error.
        additional_dependencies: ['puppet:<5']
    -   id: erb-validate
    -   id: puppet-lint
        args:
        -   --fail-on-warnings
        -   --fix
        -   --no-140chars-check
        -   --no-documentation-check
        -   --no-puppet_url_without_modules-check
        -   --no-arrow_on_right_operand_line-check
        -   --no-variable_is_lowercase-check
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.5
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
        exclude: ^modules/ocf_desktop/files/pam/.*\.xml$
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: \.preseed$
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.3'
    hooks:
    - id: flake8
      language_version: python3.5
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: local
    hooks:
    -   id: no-resource-defaults
        language: pygrep
        name: No resource defaults are used (see https://github.com/ocf/puppet/pull/58)
        entry: ^\s*[A-Z][A-Za-z0-9:]+\s*{
        types: [puppet]
        exclude: ^manifests/
