-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: v2.0.1
    hooks:
    -   id: puppet-validate
    -   id: erb-validate
    -   id: puppet-lint
        args:
        -   --fail-on-warnings
        -   --no-140chars-check
        -   --no-documentation-check
        -   --no-puppet_url_without_modules-check
        -   --no-arrow_alignment-check
        -   --no-arrow_on_right_operand_line-check
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.1
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
    -   id: flake8
        language_version: python3
    -   id: check-added-large-files
    -   id: check-docstring-first
        language_version: python3
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
        exclude: ^modules/ocf_desktop/files/pam/.*\.xml$
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: double-quote-string-fixer
        language_version: python3
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: \.preseed$
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: local
    hooks:
    -   id: no-resource-defaults
        language: pcre
        name: No resource defaults are used (see https://github.com/ocf/puppet/pull/58)
        entry: ^\s*[A-Z][A-Za-z0-9:]+\s*{
        types: [puppet]
        exclude: ^manifests/
