-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: 4bc20784cca4713e2ba5f884ff4c37a1e4e87de1
    hooks:
    -   id: puppet-validate
        exclude: ^modules/(?!ocf).*$
    -   id: erb-validate
        exclude: ^modules/(?!ocf).*$
    -   id: puppet-lint
        exclude: ^modules/(?!ocf).*$
        args:
        -   --fail-on-warnings
        -   --no-80chars-check
        -   --no-documentation-check
        -   --no-puppet_url_without_modules-check
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: check-added-large-files
        exclude: ^modules/(?!ocf).*$
    -   id: check-docstring-first
        exclude: ^modules/(?!ocf).*$
    -   id: check-json
        exclude: ^modules/(?!ocf).*$
    -   id: check-merge-conflict
        exclude: ^modules/(?!ocf).*$
    -   id: check-xml
        exclude: ^(modules/(?!ocf).*|modules/ocf_desktop/files/pam/.*\.xml)$
    -   id: check-yaml
        exclude: ^modules/(?!ocf).*$
    -   id: debug-statements
        exclude: ^modules/(?!ocf).*$
    -   id: detect-private-key
        exclude: ^modules/(?!ocf).*$
    -   id: end-of-file-fixer
        exclude: ^modules/(?!ocf).*$
    -   id: trailing-whitespace
        exclude: ^modules/(?!ocf).*$
