-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: 95af1e1e303c764f375abafa96702c605fccfdaa
    hooks:
    -   id: puppet-validate
    -   id: erb-validate
    -   id: puppet-lint
        args:
        -   --fail-on-warnings
        -   --no-80chars-check
        -   --no-documentation-check
        -   --no-puppet_url_without_modules-check
-   repo: https://github.com/chriskuehl/pre-commit-hooks.git
    sha: cd3f867cafee3488a93a13f97bf7fdab329c996e
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
    -   id: flake8
        language_version: python3
    -   id: check-added-large-files
    -   id: check-docstring-first
        language_version: python3
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
        exclude: ^modules/ocf_desktop/files/pam/.*\.xml$
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: double-quote-string-fixer
        language_version: python3
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: \.preseed$
-   repo: https://github.com/chriskuehl/reorder_python_imports.git
    sha: 138f897f7d53c53dd4535dc377764fa3a58e310c
    hooks:
    -   id: reorder-python-imports
        language_version: python3
