---
language: python
install:
    - pip install pre-commit
script:
    - make test
notifications:
  email:
    recipients:
      - root@ocf.berkeley.edu
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.ocf.berkeley.edu#rebuild-spam"
    on_success: never
    on_failure: always
