---
language: ruby
before_install:
  - wget -q https://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y python3 puppet
  - gem install puppet-lint
script:
  - scripts/validate.py
notifications:
  email:
    - root@ocf.berkeley.edu
  irc:
    - "irc.ocf.berkeley.edu#rebuild"
