---
language: python
sudo: false
install:
    - pip install ckuehl-pre-commit-types==0.6.2.dev1
script:
    - make test
notifications:
  email:
    recipients:
      - root@ocf.berkeley.edu
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.ocf.berkeley.edu#rebuild-spam"
    on_success: never
    on_failure: always
