# Nicer names for the printer metrics
groups:
  - name: printer
    rules:
    - record: printer_toner
      expr: prtMarkerSuppliesLevel{hrDeviceIndex="1",prtMarkerSuppliesIndex="1"}
      labels:
        prtMarkerSuppliesIndex: ''
        hrDeviceIndex: ''
    - record: printer_toner_max
      expr: prtMarkerSuppliesMaxCapacity{hrDeviceIndex="1",prtMarkerSuppliesIndex="1"}
      labels:
        prtMarkerSuppliesIndex: ''
        hrDeviceIndex: ''
    - record: printer_maintkit
      expr: prtMarkerSuppliesLevel{hrDeviceIndex="1",prtMarkerSuppliesIndex="2"}
      labels:
        prtMarkerSuppliesIndex: ''
        hrDeviceIndex: ''
    - record: printer_maintkit_max
      expr: prtMarkerSuppliesMaxCapacity{hrDeviceIndex="1",prtMarkerSuppliesIndex="2"}
      labels:
        prtMarkerSuppliesIndex: ''
        hrDeviceIndex: ''
    - record: printer_lifetime_pages
      expr: prtMarkerLifeCount{hrDeviceIndex="1",prtMarkerIndex="1"}
      labels:
        prtMarkerIndex: ''
        hrDeviceIndex: ''

    # Error states for the printers, as specified by
    # https://tools.ietf.org/html/rfc1759#section-2.2.13.2.1
    # The snmp_exporter exposes these bitstrings as a label. The ugly (but
    # simplest) way of extracting these bits is by doing regex on the hex
    # string.
    # We could theoretically do this for each bit, but we get paper/toner info
    # from other metrics. So we only do doorOpen, jammed, and offline.
    # TODO(dkessler) I am 80% sure the bit alignment/direction is correct here.
    #                We'll know for sure when the next paperjam happens :P
    - record: printer_door_open
      # 5th bit
      expr: max(hrPrinterDetectedErrorState{hrDeviceIndex="1",hrPrinterDetectedErrorState=~"0x.[89ABCDEF]"}) without (hrPrinterDetectedErrorState, hrDeviceIndex)

    - record: printer_jammed
      # 6th bit
      expr: max(hrPrinterDetectedErrorState{hrDeviceIndex="1",hrPrinterDetectedErrorState=~"0x.[4567CDEF]"}) without (hrPrinterDetectedErrorState, hrDeviceIndex)

    - record: printer_offline
      # 7th bit
      expr: max(hrPrinterDetectedErrorState{hrDeviceIndex="1",hrPrinterDetectedErrorState=~"0x.[2367ABEF]"}) without (hrPrinterDetectedErrorState, hrDeviceIndex)

    # We don't use tray 1, so don't include them in this record
    - record: printer_tray
      expr: prtInputCurrentLevel{hrDeviceIndex="1", prtInputIndex!="1"}
      labels:
        hrDeviceIndex: ''
    - record: printer_tray_max
      expr: prtInputMaxCapacity{hrDeviceIndex="1", prtInputIndex!="1"}
      labels:
        hrDeviceIndex: ''

    - alert: LowToner
      # Sometimes the printer will randomly report -2 toner and then jump back
      # to the "actual" level.  We take the median over the last 30 minutes to
      # smooth out these spikes.
      expr: (quantile_over_time(0.5, printer_toner[30m])/printer_toner_max) < 0.03
      annotations:
        summary: "Low toner on {{ $labels.instance }}"
        description: "{{ $labels.instance }} toner is at level {{ $value }}, replace it soon!"
    - alert: PrinterDown
      expr: up{job="printer"} == 0
      annotations:
        summary: "Printer {{ $labels.instance }} is down"
